# Site settings
title: Sahil Patel
name: Sahil Patel

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/sahildpatel

#Any buzzword skills you want to include
skills:
 - Excel
 - SQL
 - R
 - Salesforce
 - Google BigQuery
 - GoodData
 - STATA
 
#Work experience is required
experience:
 - title: Business Analyst Intern
   start: June 2017
   end: May 2018
   employer: Zendesk
   description: Analyzed product data to understand monetization strategy for the freemium plan for the Zendesk Talk product. Conclusion led to key strategic decisions around the future of the plan. Presented Zendesk Talk data for weekly and monthly management meetings. Created Salesforce reports to enable sales specialists to more efficiently evaluate performance. Designed a dashboard in Zendesk Explore to display Zendesk Talk data from various sources in a consolidated view for internal teams to use. Provided continued part-time support as the only intern from the cohort to work remotely during the school year.
 - title: Business Development Intern
   start: June 2016
   end: December 2016
   employer: Helios RE LLC
   description: Created investor pitches, developed a business strategy, and worked to establish a MVP through the Cleantech Organization’s accelerator program. Designed an outreach program to gauge market interest in product features. Collaborated with CEO and engineers to propose product improvements to increase potential customers.
 - title: Client Relations Intern
   start: June 2016
   end: August 2016
   employer: Regreen Technologies
   description: Produced product videos to convey Regreen’s value proposition to prospective clients from El Salvador and Singapore. Edited patent to further assist the team.

#Education is required
education:
 - level: Bachelor of Arts (BA)
   subject: Economics
   date: May 2019
   school: University of California, Berkeley
   gpa: 3.56

extracurriculars:
- organization: The Berkeley Project
  title: Financial Affairs Committee Member
  dates: January 2018 &#x2010 present
  description: Managed budgets for various committees to plan annual spending. Secured sponsorships from local businesses and corporations.
- organization: Berkeley Technology Review
  title: Marketing Lead
  dates: August 2016 &#x2010 present
  description: Developed a social media marketing strategy to increase readership of online and print publications. Established a marketing plan to tap into UC Berkeley’s population of writers and expand BTR’s content production.  

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
#additionalinfo: |
  # <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others.  In my current role Groovy is the primary language used - and I am familiar with many of the languages features and quirks (including writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>). <br/><br/>
   #<strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC framework (although current role uses ColdFusion for server side web stack). I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   #<strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   #I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
   #As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
   #I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
