# Site settings
title: Sahil Patel
name: Sahil Patel

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/sahildpatel
 - title: Email
   url: mailto:sahildp44@gmail.com
 - title: Salesforce Verification
   url: http://certification.salesforce.com/verification-email?init=1&email=sahildp44@gmail.com

#Any buzzword skills you want to include
skills:
 - Certified Salesforce Administrator
 - Excel
 - Google Sheets
 - MySQL
 - R
 - STATA
 - Google BigQuery
 - Google Analytics
 
#Work experience is required
experience:
 - title: SDR & Sales Operations Intern
   start: May 2018
   end: Present
   employer: Worklete
   description: <ul> <li>Set 51 meetings over 6 weeks to create a sales pipeline of over $1,000,000 and drive new business growth. </li> <li> Deployed and managed Salesforce as Salesforce Admin to optimize sales process and improve pipeline tracking. </li> <li> Created custom fields and reports in Salesforce to enable more detailed reporting on deals and leads. </li> <li> Analyzed injury data from clients to aid with customer success by providing evidence of successful injury reduction. </li> <li> Created sales performance reports for board of directors using Salesforce data to summarize future revenue growth. </li> <li> Providing continued support for Sales Operations and Data Analytics as a full-time student. </li> <li> Spearheaded SDR program as first SDR by developing a playbook for sales team and leading outreach campaigns. </li> </ul>
 - title: Salesforce Consultant
   start: August 2018
   end: Present
   employer: The Bulk Bag Company
   description: <ul> <li> Decreased time spent managing Salesforce data by 50% by implementing best practices for Sales team. </li> <li> Created custom reports for Sales team to easily track deals, leads, and customers. </li> <li> Set up integrations with marketing software to increase efficiency of email campaigns. </li> <li> Improved data management to mitigate issues with duplicate and incomplete records. </li> </ul>
 - title: Business Analyst Intern
   start: June 2017
   end: March 2018
   employer: Zendesk
   description: <ul> <li> Analyzed product data to understand monetization strategy for the freemium plan for the Zendesk Talk product. </li> <li> Conclusion led to key strategic decisions around the future of the plan. </li> <li> Presented Zendesk Talk data for weekly and monthly management meetings. </li> <li> Created Salesforce reports to enable sales specialists to more efficiently evaluate performance. </li> <li> Designed a dashboard in Zendesk Explore to display Zendesk Talk data from various sources in a consolidated view for internal teams to use. </li> <li> Provided continued part-time support as the only intern from the cohort to work remotely during the school year. </li> </ul>
 - title: Business Development Intern
   start: June 2016
   end: December 2016
   employer: Helios RE LLC
   description: <ul> <li> Created investor pitches, developed a business strategy, and worked to establish a MVP through the Cleantech Organization’s accelerator program. </li> <li> Designed an outreach program to gauge market interest in product features. </li> <li> Collaborated with CEO and engineers to propose product improvements to increase potential customers. </li> </ul>
 - title: Client Relations Intern
   start: June 2016
   end: August 2016
   employer: Regreen Technologies
   description: <ul> <li> Produced product videos to convey Regreen’s value proposition to prospective clients from El Salvador and Singapore. </li> <li> Edited patent to further assist the team. </li> </ul>

#Education is required
education:
 - level: Bachelor of Arts (BA)
   subject: Economics
   date: May 2019
   school: University of California, Berkeley
   gpa: 3.62

extracurriculars:
- organization: The Berkeley Project
  title: Financial Affairs Committee Member
  dates: January 2018 - present
  description: <ul> <li>Managed budgets for various committees to plan annual spending</li> <li>Secured sponsorships from local businesses and corporations. </li> <li> Wrote grant applications to secure funding from UC Berkeley and City of Berkeley. </li> </ul>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
#additionalinfo: |
  # <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others.  In my current role Groovy is the primary language used - and I am familiar with many of the languages features and quirks (including writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>). <br/><br/>
   #<strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC framework (although current role uses ColdFusion for server side web stack). I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   #<strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   #I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
   #As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
   #I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
